import type { Metadata } from "next";
import { Readex_Pro } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "sonner";

const readex = Readex_Pro({
  subsets: ["latin", "arabic"],
  variable: "--font-geist-sans",
  weight: ["400", "500", "700"],
  preload: true,
});
export const metadata: Metadata = {
  title: "التمويل الالكتروني | تمويل يصل الي 6 مليون",
  description: "Generated by create next app",
  icons: "/images/logo.jpeg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${readex.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReactQueryProvider>
          {children}
          <Toaster
            richColors
            position="top-center"
            duration={3000}
            closeButton={true}
          />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
